const colorNames = {};

const coolNames = [
  "Arcana", "Wyrd", "Sorcery", "Hex", "Glamour", "Mysteria", "Eldritch", "Runebound",
  "Thaum", "Faerie", "Grimoire", "Spellbound", "Leyline", "Umbral", "Charmed",

  // —— แนวจักรวาล/อวกาศ เพิ่มเติม ——  
  "Pulsar", "Singularity", "Antimatter", "Redshift", "Blueshift", "Darkmatter", "Exoplanet",
  "Starfall", "Hypernova", "Supernova", "Aurora", "Photon", "Radiant", "Quintessence",
  "Gravity", "Nebulon", "Orion", "Andromeda", "Celestium", "Metagalaxy",

  // —— แนวศิลป์/เฉดสี เพิ่มเติม ——  
  "Pastel", "Watercolor", "Oilspill", "Graffiti", "Stencil", "Monochrome", "Duotone",
  "Gradient", "Impression", "Expression", "Mosaic", "Collage", "Stencil", "Pointillism",
  "Silkscreen", "Charcoal", "Inkblot", "Scrawl", "Marbling", "Etching",

  // —— แนวธรรมชาติ/แสงเงา เพิ่มเติม ——  
  "Gale", "Monsoon", "Zephyr", "Cyclone", "Hurricane", "Tornado", "Aurora", "Glacier",
  "Oasis", "Savanna", "Prairie", "Thicket", "Glade", "Mire", "Fen", "Tundra", "Savage",
  "Canopy", "Underbrush", "Highland",

  // —— แนวเทคโนโลยี/ไซไฟ เพิ่มเติม ——  
  "Nanobot", "Biohack", "Cyberia", "Voxel", "Bitstream", "Overclock", "QuantumFlux",
  "Psion", "Mechanoid", "Cyberia", "Datacenter", "PulseCore", "Servo", "Hologram",
  "Augment", "Interface", "Firewall", "Bootstrap", "Kernel", "Fragment",

  // —— แนวทะเล/น้ำ เพิ่มเติม ——  
  "Tide", "Current", "Surf", "Breaker", "Coral", "Kelp", "Brine", "Abyss", "Lagoon",
  "Reef", "Splash", "Grotto", "Mariner", "Nautilus", "Trench", "Bluehole", "Estuary",
  "Ripcurl", "Spray", "Eddy",

  // —— แนวพฤกษศาสตร์/ดอกไม้ เพิ่มเติม ——  
  "Petal", "Blossom", "Foliar", "Vine", "Thorn", "Bramble", "Fern", "Moss", "Lichen",
  "Cactus", "Succulent", "Orchid", "Lotus", "Peony", "Azalea", "Magnolia", "Camellia",
  "Dahlia", "Iris", "Poppy",

  // —— แนวสัตว์/ชีวภาพ เพิ่มเติม ——  
  "Feather", "Fang", "Claw", "Scale", "Mane", "Shell", "Antenna", "Hive", "Pollen",
  "Fur", "Quill", "Spore", "Wing", "Beak", "Tusks", "Branchia", "Carapace", "Plume",
  "Mandible", "Talons",
  "Arcane",
  "Mystic",
  "Enchant",
  "Ether",
  "Astral",
  "Rune",
  "Spirit",
  "Phantom",
  "Hexa",
  "Charm",
  "Halo",
  "Mirage",
  "Orb",
  "Aura",
  "Element",
  "Echo",
  "Fable",
  "Sigil",
  "Vortex",
  "Portal",
  "Arcana",
  "Wyrd",
  "Sorcery",
  "Hex",
  "Glamour",
  "Mysteria",
  "Eldritch",
  "Runebound",
  "Thaum",
  "Faerie",
  "Grimoire",
  "Spellbound",
  "Leyline",
  "Umbral",
  "Charmed",
  "Nova",
  "Nebula",
  "Comet",
  "Meteor",
  "Quasar",
  "Cosmos",
  "Galaxy",
  "Void",
  "Eclipse",
  "Starlight",
  "Solar",
  "Lunar",
  "Celestia",
  "Orbit",
  "Zenith",
  "Astro",
  "Plasma",
  "Spectrum",
  "Blackhole",
  "Pulse",
  "Pulsar",
  "Singularity",
  "Antimatter",
  "Redshift",
  "Blueshift",
  "Darkmatter",
  "Exoplanet",
  "Starfall",
  "Hypernova",
  "Supernova",
  "Aurora",
  "Photon",
  "Radiant",
  "Quintessence",
  "Gravity",
  "Nebulon",
  "Orion",
  "Andromeda",
  "Celestium",
  "Metagalaxy",
  "Tint",
  "Hue",
  "Tone",
  "Chroma",
  "Swatch",
  "Canvas",
  "Blend",
  "Pigment",
  "Palette",
  "Saturate",
  "Overlay",
  "Filter",
  "Sketch",
  "Doodle",
  "Brush",
  "Spray",
  "Splash",
  "Varnish",
  "Fresco",
  "Glaze",
  "Pastel",
  "Watercolor",
  "Oilspill",
  "Graffiti",
  "Stencil",
  "Monochrome",
  "Duotone",
  "Gradient",
  "Impression",
  "Expression",
  "Mosaic",
  "Collage",
  "Pointillism",
  "Silkscreen",
  "Charcoal",
  "Inkblot",
  "Scrawl",
  "Marbling",
  "Etching",
  "Mist",
  "Fog",
  "Cloud",
  "Rain",
  "Breeze",
  "Dust",
  "Ember",
  "Flame",
  "Glow",
  "Ray",
  "Beam",
  "Flicker",
  "Flash",
  "Shine",
  "Spark",
  "Twilight",
  "Dusk",
  "Dawn",
  "Blizzard",
  "Drift",
  "Gale",
  "Monsoon",
  "Zephyr",
  "Cyclone",
  "Hurricane",
  "Tornado",
  "Glacier",
  "Oasis",
  "Savanna",
  "Prairie",
  "Thicket",
  "Glade",
  "Mire",
  "Fen",
  "Tundra",
  "Canopy",
  "Underbrush",
  "Highland",
  "Pixel",
  "Circuit",
  "Byte",
  "Signal",
  "Flux",
  "Core",
  "Data",
  "Glitch",
  "Phase",
  "Neuron",
  "Synth",
  "Module",
  "Chip",
  "Laser",
  "Drone",
  "Techno",
  "Pulsewave",
  "Mecha",
  "Volt",
  "Neural",
  "Nanobot",
  "Biohack",
  "Cyberia",
  "Voxel",
  "Bitstream",
  "Overclock",
  "QuantumFlux",
  "Psion",
  "Mechanoid",
  "Datacenter",
  "PulseCore",
  "Servo",
  "Hologram",
  "Augment",
  "Interface",
  "Firewall",
  "Bootstrap",
  "Kernel",
  "Fragment",
  "Tide",
  "Current",
  "Surf",
  "Breaker",
  "Coral",
  "Kelp",
  "Brine",
  "Abyss",
  "Lagoon",
  "Reef",
  "Grotto",
  "Mariner",
  "Nautilus",
  "Trench",
  "Bluehole",
  "Estuary",
  "Ripcurl",
  "Spray",
  "Eddy",
  "Petal",
  "Blossom",
  "Foliar",
  "Vine",
  "Thorn",
  "Bramble",
  "Fern",
  "Moss",
  "Lichen",
  "Cactus",
  "Succulent",
  "Orchid",
  "Lotus",
  "Peony",
  "Azalea",
  "Magnolia",
  "Camellia",
  "Dahlia",
  "Iris",
  "Poppy",
  "Feather",
  "Fang",
  "Claw",
  "Scale",
  "Mane",
  "Shell",
  "Antenna",
  "Hive",
  "Pollen",
  "Fur",
  "Quill",
  "Spore",
  "Wing",
  "Beak",
  "Tusks",
  "Branchia",
  "Carapace",
  "Plume",
  "Mandible",
  "Talons",
];

// สร้างชื่อสีแบบรวมคำ 2 คำ
function generateComboName() {
  let first = "", second = "";
  do {
    first = coolNames[Math.floor(Math.random() * coolNames.length)];
    second = coolNames[Math.floor(Math.random() * coolNames.length)];
  } while (first === second); // ห้ามซ้ำกัน
  return first + second;
}

// สร้างชื่อให้กับ 400 สี
for (let i = 0; i < 400; i++) {
  const hex = '#' + Math.floor(Math.random() * 0xFFFFFF).toString(16).padStart(6, '0');
  const bigint = parseInt(hex.slice(1), 16);
  const r = (bigint >> 16) & 255;
  const g = (bigint >> 8) & 255;
  const b = bigint & 255;
  const key = [r, g, b].join(',');
  const name = generateComboName();
  colorNames[key] = name;
}

console.log(Object.keys(colorNames).length + " colors total");
window.colorNames = colorNames;
